### ISSUE TITLE
Python raw_input crashes in FireFox

### ISSUE THREAD

**Issue by ZaliZat** [replit/repl.it#144]
```
bar = raw_input('foo:')
print bar
```

Causes repl.it to crash. A dialogue box pops up that says: "The program is taking too long to finish. Do you want to stop it?" Sometimes it will work on the first raw_input, but it slows/crashes on later inputs.

**Comment by amasad** [comment]
cc @masad-frost can you take a look?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, this appears to have been fixed. :)
