### ISSUE TITLE
Add title and tag edit functions to current session page.

### ISSUE THREAD

**Issue by lsloan** [replit/repl.it#152]
While it's great that sessions can have titles and tags, it would be extremely helpful if those fields were visible and could be edited in the current session without bringing up the list of all other sessions.  For example, beside the name of the language of the current session at the top of the page, also show the title and tags if they have been set.  Show placeholders if they haven't been set.  Clicking on the title, tags, or their placeholders would bring up edit fields to change or add values.

**Comment by amasad** [comment]
cc @masad-frost @hayaodeh

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

(titles can now be edited from within a repl as well)
