### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by amasad** [replit/repl.it#156]
We are not even on the first 10 pages for:
- run code online
- Online compiler 
- Online ide

etc :(

Maybe we started doing even worse since we stopped doing any kind of server rendering.

**Comment by amasad** [comment]
we are doing well for things like: "online python"

**Comment by ajkamel** [comment]
Just was cruising through and saw this... SEO is often such a hard thing to gauge or measure but Moz tends to have good articles from people that are focused on optimizing for things like this.  https://moz.com/beginners-guide-to-seo could be a nice overview on the subject.

**Comment by amasad** [comment]
Nice. Thanks Ash!

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, our SEO seems to have improved in the last year :)
