### ISSUE TITLE
Can't copy/paste code from repl.it

### ISSUE THREAD

**Issue by harvey56** [replit/repl.it#157]
Hi,

I can paste code to repl.it, but not from repl.it. Cut/Copy/Paste code from repl.it to another line in the same worksheet does not work either.
This is when working Javascript code on Firefox.

**Comment by Polyergic** [comment]
Copy/paste within a repl.it editor also doesn't work in Chrome

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, this appears to have been fixed. :)
