### ISSUE TITLE
C math library functions

### ISSUE THREAD

**Issue by oldtimer2** [replit/repl.it#171]
How do I access math functions from math.h? Allows me to include math.h, but get an "undefined reference" trying to use sin(), pow(), sqrt(), etc.
I'm just wanting to use this for introductory C. 
Thank you

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

For this particular issue - I'm not as familiar with C - someone on our feedback board should be able to help you as well.
