### ISSUE TITLE
Lua tostring metamethod does not work

### ISSUE THREAD

**Issue by nathanmerrill** [replit/repl.it#180]
I've created the following code:
```lua
local a = {}
local mt = {}
function mt:__tostring()
  return "Nil"
end
setmetatable(a, mt)
print(a)
```

Which should print out "Nil", but prints out the table.  However, the above code is correct, and works on on other interpreters.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

I've also submitted this bug to our internal tracking system.
