### ISSUE TITLE
THE QBASIC interpreter fails to interpret a simple "if...then... else...." statement

### ISSUE THREAD

**Issue by officialaimm** [replit/repl.it#188]
For example: https://repl.it/KKjf/2 This code fails to be parsed even though it  is syntactically correct.... It complains of seeing a token "PRINT" but it is quite expected!! Please fix it. 

-Thank you!

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

I've also submitted this issue to our internal tracking system
