### ISSUE TITLE
Got a problem with python

### ISSUE THREAD

**Issue by jwdmo** [replit/repl.it#189]
Each time when I open a new project in python, the python shell won't load properly. Btw other languages are working just fine but I installed Replit because of python ide and unfortunately it doesn't seem working fine.

 Any other guys're facing this problem ?
      What's the solution ?

**Comment by amasad** [comment]
Hey @IamJavid this the first time we hear of this problem. It's working fine on my end.
Can you please do the following to be able to help you troubleshoot it:

1. Explain the problem in more details (what is expected vs what do you see). Gifs and screenshots would be appreciate it
2. What's your operating system and browser versions?
3. Open the JavaScript console and check for any errors (and paste her)

**Comment by IamJavid** [comment]
![untitled](https://user-images.githubusercontent.com/16553195/29654607-1c078f86-88c3-11e7-9f5a-90eaa5f9141f.png)
Hi @amasad 


As you can see above progress bar stuck. the app is running on ubnutu 16.04, client's os is windows7 and i'm using chrome btw i think it's a server side problem because i asked some friends to check it out and they just reported the samething. [I saw a closed issue that is similar to my problem](https://github.com/replit/repl.it/issues/146)
i really didn't get them what happened so they closed the issue without any solution !
I would appreciate it if i know what i have to do to solve it. 

Thank you for fast responding.

**Comment by jwdmo** [comment]
Dear @amasad 

I'm still waiting for your answer if there is no way at least tell me to find something else or take another action that may help me.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

@jwdmo - please let us know if you are still having this issue.
