### ISSUE TITLE
ES6 `let` broken in Replit JS console in Web Project environment

### ISSUE THREAD

**Issue by benjaminEwhite** [replit/repl.it#190]
When included in the left panel (for writing code), `let` works as expected, but when using the interactive JS console, there's a bug.

Specifically, if you set value of a variable declared with `let` to any data type other than string, you get a reference error when referring to it (despite fact that assignment appears to work fine).

![bug](https://user-images.githubusercontent.com/960351/30127498-83fddf42-930d-11e7-8015-b193c0b3c9fc.gif)

**Comment by SaraJo** [comment]
+1

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, this appears to have been fixed. :)
