### ISSUE TITLE
Module names is not working in Python3

### ISSUE THREAD

**Issue by AlineThorns** [replit/repl.it#191]
The module names in on the list of librarys, but this don't work.

**Comment by Forsaiken** [comment]
I have the same problem.

**Comment by cyarbrough22** [comment]
Same here. Anyone hear of a fix?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, I've added this to our list of python modules to include. :)
