### ISSUE TITLE
gTTS in import dialog but throws error when imported

### ISSUE THREAD

**Issue by JoeZwet** [replit/repl.it#192]
Python Code:
```python
import gTTS
import os

dir_path = os.path.dirname(os.path.realpath(__file__))
tts = gTTS(text='Welcome', lang='en')
tts.save(dir_path + "/text.mp3")
```
this throws an error in console when importing gtts.

Error:
```
Traceback (most recent call last):
  File "python", line 1, in <module>
ModuleNotFoundError: No module named 'gtts'
```

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, I've added this to our list of python modules to include. :)
