### ISSUE TITLE
Issue when importing enums, when inside a project

### ISSUE THREAD

**Issue by Zwork101** [replit/repl.it#193]
Inside one of my projects, I'm importing the the enum modual. However, on import, it throws this error: 
```python
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from types import *
  File "/home/runner/types.py", line 1, in <module>
    import enum # learn more: https://python.org/pypi/enum
  File "/usr/local/lib/python3.6/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType'
``` 
I went into another repl, one not a project, and in the command line, I tried the code that had an Import Error. 
```python
   from types import MappingProxyType
   MappingProxyType
=> <class 'mappingproxy'>
   ``` 
Any idea what's happening? I might be something with the container, but It's become an issue

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, I believe this has been fixed. :)
