### ISSUE TITLE
Python code in an embedded repl.it snippet prints "None" at end when ran

### ISSUE THREAD

**Issue by misingnoglic** [replit/repl.it#198]
Example: 

`<script src="//repl.it/embed/OAK4/0.js"></script>`

Looks like this when embedded and run: https://imgur.com/a/xkPca

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Also, this seems to be working for me when I use the <iframe> embed method.
