### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by ssameerr** [replit/repl.it#199]
Does replit support Tensorflow and other ML libraries?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Re: this issue in particular - not all libraries are available yet, but we are looking to include them in the future!
