### ISSUE TITLE
Error while importing sklearn in repl.it (py3)

### ISSUE THREAD

**Issue by darkenlightenment** [replit/repl.it#202]
Running Python 3.6.1 on linux:
For:
from sklearn import datasets as db

Error shown: 
File "python", line 1, in <module>
File "/goval_modules/python3.6/urllib2.py", line 220
    raise AttributeError, attr
                                  ^
SyntaxError: invalid syntax

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

I've also added this to our internal tracking system.
