### ISSUE TITLE
In classroom assignments, files were bleeding into other assignments

### ISSUE THREAD

**Issue by PyleOfBytes** [replit/repl.it#205]
On the classroom version of repl.it, txt files from one assignment appeared in other assignments using project mode.

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

Please feel free to contact me further at tim@repl.it about this bug - would love more details about it and steps to replicate if you have them.
