### ISSUE TITLE
Accessibility and the shell's traceback

### ISSUE THREAD

**Issue by seraries** [replit/repl.it#207]
Hello! I really love repl.it and am using it as an embed in an online class I'm developing, but I have gotten feedback from color blind students that they cannot read the traceback error messages in the console since it is reddish text on a black background. Is there any way to customize this?

**Comment by timmyichen** [comment]
We're closing this issue because this repo has been deprecated for some time now - for further suggestions, please submit them to our Feedback board where users can vote for them: [https://repl.it/feedback](https://repl.it/feedback) (bug reports go there too!)

I've also added this to our internal tracker. :)
